// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright 2026 Benjamin Bellamy

package scanner

import (
	"context"
	"encoding/base64"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestUdevScannerSkipsOwnedAndNonRules(t *testing.T) {
	dir := t.TempDir()
	prevDir := udevRulesDir
	udevRulesDir = dir
	defer func() { udevRulesDir = prevDir }()

	// Three real rules + decoy files. The "owned" one will be flagged by
	// the stubbed dpkgOwnedPaths and dropped.
	files := map[string]string{
		"50-qmk.rules":       "SUBSYSTEM==\"hidraw\", MODE=\"0660\", GROUP=\"plugdev\"\n",
		"60-cdrom_id.rules":  "# shipped by udev package — should be skipped\n",
		"99-platformio.rules": "ATTRS{idVendor}==\"0483\", MODE=\"0666\"\n",
		"README.txt":         "not a rules file — should be ignored",
		".hidden.rules":      "dotfile — should be ignored",
	}
	for name, body := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	ownedPath := filepath.Join(dir, "60-cdrom_id.rules")
	prevDpkg := dpkgOwnedPaths
	dpkgOwnedPaths = func(paths []string) map[string]bool {
		// Assert the scanner batched all .rules candidates into a single call.
		seen := map[string]bool{}
		for _, p := range paths {
			seen[p] = true
		}
		want := []string{
			filepath.Join(dir, "50-qmk.rules"),
			filepath.Join(dir, "60-cdrom_id.rules"),
			filepath.Join(dir, "99-platformio.rules"),
		}
		for _, w := range want {
			if !seen[w] {
				t.Errorf("dpkgOwnedPaths missing candidate %q", w)
			}
		}
		if len(paths) != len(want) {
			t.Errorf("dpkgOwnedPaths called with %d paths, want %d", len(paths), len(want))
		}
		return map[string]bool{ownedPath: true}
	}
	defer func() { dpkgOwnedPaths = prevDpkg }()

	pkgs, err := UdevScanner{}.Scan(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if len(pkgs) != 2 {
		for _, p := range pkgs {
			t.Logf("got: %s · %s", p.Name, p.Evidence)
		}
		t.Fatalf("got %d packages, want 2", len(pkgs))
	}

	wantNames := map[string]string{
		"50-qmk.rules":        files["50-qmk.rules"],
		"99-platformio.rules": files["99-platformio.rules"],
	}
	for _, p := range pkgs {
		body, ok := wantNames[p.Name]
		if !ok {
			t.Errorf("unexpected name: %q", p.Name)
			continue
		}
		if p.ID != "udev:"+p.Name {
			t.Errorf("%s: ID = %q, want %q", p.Name, p.ID, "udev:"+p.Name)
		}
		if p.Evidence != filepath.Join(dir, p.Name) {
			t.Errorf("%s: Evidence = %q, want under %q", p.Name, p.Evidence, dir)
		}
		decoded, derr := base64.StdEncoding.DecodeString(p.Payload)
		if derr != nil {
			t.Errorf("%s: payload decode: %v", p.Name, derr)
			continue
		}
		if string(decoded) != body {
			t.Errorf("%s: payload = %q, want %q", p.Name, decoded, body)
		}
	}
}

func TestUdevScannerSkipsAutoGenerated(t *testing.T) {
	dir := t.TempDir()
	prevDir := udevRulesDir
	udevRulesDir = dir
	defer func() { udevRulesDir = prevDir }()

	// Three real rules; two are machine-generated (snapd + curtin) so they
	// must be dropped even though dpkg doesn't own them.
	files := map[string]string{
		"50-qmk.rules":          "KERNEL==\"hidraw*\", MODE=\"0660\", GROUP=\"plugdev\"\n",
		"70-snap.firefox.rules": "# This file is automatically generated.\nKERNEL==\"video[0-9]*\", TAG+=\"snap_firefox_firefox\"\n",
		"ubuntu--vg-ubuntu--lv.rules": "# Written by curtin\nSUBSYSTEM==\"block\", ENV{DM_NAME}==\"ubuntu--vg-ubuntu--lv\"\n",
	}
	for name, body := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	prevDpkg := dpkgOwnedPaths
	dpkgOwnedPaths = func(paths []string) map[string]bool { return nil } // nothing apt-owned
	defer func() { dpkgOwnedPaths = prevDpkg }()

	pkgs, err := UdevScanner{}.Scan(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if len(pkgs) != 1 || pkgs[0].Name != "50-qmk.rules" {
		for _, p := range pkgs {
			t.Logf("got: %s", p.Name)
		}
		t.Fatalf("got %d packages, want only 50-qmk.rules", len(pkgs))
	}
}

func TestIsAutoGeneratedRule(t *testing.T) {
	cases := []struct {
		name string
		body string
		want bool
	}{
		{"snapd", "# This file is automatically generated.\nKERNEL==…\n", true},
		{"curtin", "# Written by curtin\nSUBSYSTEM==…\n", true},
		{"user-written QMK", "# Keychron / QMK keyboards\nKERNEL==…\n", false},
		{"empty", "", false},
		{"marker buried past 1 KiB", strings.Repeat("# user comment\n", 100) + "# This file is automatically generated.\n", false},
	}
	for _, c := range cases {
		if got := isAutoGeneratedRule([]byte(c.body)); got != c.want {
			t.Errorf("%s: isAutoGeneratedRule = %v, want %v", c.name, got, c.want)
		}
	}
}

func TestUdevScannerEmptyDir(t *testing.T) {
	dir := t.TempDir()
	prevDir := udevRulesDir
	udevRulesDir = dir
	defer func() { udevRulesDir = prevDir }()

	prevDpkg := dpkgOwnedPaths
	dpkgOwnedPaths = func(paths []string) map[string]bool {
		if len(paths) != 0 {
			t.Errorf("expected no candidates, got %v", paths)
		}
		return nil
	}
	defer func() { dpkgOwnedPaths = prevDpkg }()

	pkgs, err := UdevScanner{}.Scan(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if len(pkgs) != 0 {
		t.Fatalf("got %d packages from empty dir, want 0", len(pkgs))
	}
}

func TestUdevScannerAvailable(t *testing.T) {
	dir := t.TempDir()
	prevDir := udevRulesDir
	udevRulesDir = dir
	defer func() { udevRulesDir = prevDir }()

	if !(UdevScanner{}).Available() {
		t.Errorf("Available() = false for an existing dir, want true")
	}

	udevRulesDir = filepath.Join(dir, "does-not-exist")
	if (UdevScanner{}).Available() {
		t.Errorf("Available() = true for a missing dir, want false")
	}
}
