// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright 2026 Benjamin Bellamy

package scanner

import (
	"bytes"
	"context"
	"encoding/base64"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/benjaminbellamy/reliure/internal/snapshot"
)

// udevRulesDir is the system location for local udev rules. Overridden in
// tests.
var udevRulesDir = "/etc/udev/rules.d"

// UdevScanner captures user-installed udev rules — the files at
// /etc/udev/rules.d/*.rules that grant the desktop user permission to talk
// to USB devices without sudo (QMK keyboards, PlatformIO microcontrollers,
// ST-Link debuggers, Saleae analysers, …). These rules are typically
// dropped in place by curl|sh-style installers and aren't tracked by apt,
// so a fresh reinstall silently loses them.
//
// We deliberately ignore rules owned by apt packages: those come back via
// ``apt install`` so capturing them would just clutter the snapshot. The
// dpkg ownership query is batched into one call across every candidate
// path; the result is exposed via a package var so the test stubs it
// rather than shelling out under ``go test``.
//
// We also skip rules whose body identifies them as machine-generated —
// snapd's ``70-snap.<name>.rules`` files (header: ``# This file is
// automatically generated.``) and curtin's per-LVM-volume rules (header:
// ``# Written by curtin``). Those come back automatically from
// ``snap install`` and the Ubuntu installer respectively, so capturing
// them is noise. The marker check is content-based (not filename-based)
// so it survives renames and catches future generators that adopt the
// same self-identifying header convention.
//
// /etc/udev/rules.d/ is mode 755 with files at 644 — world-readable — so
// the scanner runs unprivileged. No SkipError plumbing.
type UdevScanner struct{}

func (UdevScanner) Name() string { return snapshot.SourceUdev }
func (UdevScanner) Available() bool {
	info, err := os.Stat(udevRulesDir)
	return err == nil && info.IsDir()
}

func (UdevScanner) Scan(_ context.Context) ([]snapshot.Package, error) {
	entries, err := os.ReadDir(udevRulesDir)
	if err != nil {
		return nil, err
	}

	candidates := []string{}
	for _, e := range entries {
		name := e.Name()
		if strings.HasPrefix(name, ".") {
			continue
		}
		if !strings.HasSuffix(name, ".rules") {
			continue
		}
		// Only regular files: a symlink to /dev/null is the standard
		// udev "this rule is disabled" marker, not something to re-install.
		info, ierr := e.Info()
		if ierr != nil || !info.Mode().IsRegular() {
			continue
		}
		candidates = append(candidates, filepath.Join(udevRulesDir, name))
	}

	owned := dpkgOwnedPaths(candidates)

	pkgs := []snapshot.Package{}
	for _, path := range candidates {
		if owned[path] {
			continue
		}
		body, rerr := os.ReadFile(path)
		if rerr != nil {
			continue
		}
		if isAutoGeneratedRule(body) {
			continue
		}
		base := filepath.Base(path)
		pkgs = append(pkgs, snapshot.Package{
			ID:       "udev:" + base,
			Name:     base,
			Source:   snapshot.SourceUdev,
			Evidence: path,
			Payload:  base64.StdEncoding.EncodeToString(body),
		})
	}
	sort.Slice(pkgs, func(i, j int) bool { return pkgs[i].Name < pkgs[j].Name })
	return pkgs, nil
}

// autoGenMarkers are header strings that generators write into their own
// rules to declare authorship. They live near the top of the file, so we
// only scan the first few lines — keeps the check cheap and avoids false
// positives from a rule that happens to contain the marker text in a
// comment further down. The list is conservative: add a new entry only
// when a generator's marker is observed in the wild.
var autoGenMarkers = [][]byte{
	[]byte("# This file is automatically generated."), // snapd
	[]byte("# Written by curtin"),                     // Ubuntu installer
}

// isAutoGeneratedRule reports whether the file body starts with a marker
// that identifies it as machine-generated. We bound the inspection to the
// first 1 KiB so a long user rule that happens to mention the marker text
// deep inside doesn't trip the filter.
func isAutoGeneratedRule(body []byte) bool {
	head := body
	if len(head) > 1024 {
		head = head[:1024]
	}
	for _, m := range autoGenMarkers {
		if bytes.Contains(head, m) {
			return true
		}
	}
	return false
}

// dpkgOwnedPaths returns the subset of ``paths`` that are owned by an
// installed apt package. Exposed as a package var so the scanner test can
// stub it rather than shell out under ``go test``. Returns an empty map
// when dpkg isn't on PATH, when there are no candidates, or when the
// dpkg call fails outright — meaning no filtering happens (all candidates
// pass through). That's the safe default: a missing dpkg means "trust the
// user's filesystem state", not "drop everything".
var dpkgOwnedPaths = func(paths []string) map[string]bool {
	if len(paths) == 0 {
		return nil
	}
	if !Have("dpkg") {
		return nil
	}
	args := append([]string{"-S"}, paths...)
	out, _ := exec.Command("dpkg", args...).Output()
	owned := map[string]bool{}
	for _, line := range strings.Split(string(out), "\n") {
		// dpkg -S prints "<package>: <path>" (and "<pkgA>, <pkgB>: <path>"
		// for diversions / multi-owned files). The path is always after
		// the last ": ".
		idx := strings.LastIndex(line, ": ")
		if idx == -1 {
			continue
		}
		p := strings.TrimSpace(line[idx+2:])
		if strings.HasPrefix(p, "/") {
			owned[p] = true
		}
	}
	return owned
}

